version: '2.1'

services:
  gateway-server:
    image: gateway-server
    container_name: gateway-server
    ports:
      - "9000:9000"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_SERV: http://eureka-server:8761/eureka/
      SERVICE_NAME: gateway-server
      SERVICE_CHECK_HTTP: /health
      ADVERTISED_HOSTNAME: gateway-server
    links:
      - rent-service
      - payment-service
      - eureka-server
      - rabbitmq
    restart: always
    depends_on:
      - eureka-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 1m30s
      timeout: 5s
      retries: 3

  rent-service:
    image: rent-service
    ports:
      - "8080"
    links:
      - eureka-server
      - rabbitmq
    environment:
      EUREKA_SERV: http://eureka-server:8761/eureka/
      SERVICE_NAME: rent-service
      SERVICE_CHECK_HTTP: /health
      ADVERTISED_HOSTNAME: rent-service
    depends_on:
      - eureka-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m30s
      timeout: 5s
      retries: 3

  payment-service:
    image: payment-service
    ports:
      - "8080"
    links:
      - eureka-server
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_SERV: http://eureka-server:8761/eureka/
      SERVICE_NAME: payment-service
      SERVICE_CHECK_HTTP: /health
      ADVERTISED_HOSTNAME: payment-service
    depends_on:
      - eureka-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m30s
      timeout: 5s
      retries: 3

  security-service:
    image: security-service
    ports:
      - "8080"
    links:
      - eureka-server
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_SERV: http://eureka-server:8761/eureka/
      SERVICE_NAME: security-service
      SERVICE_CHECK_HTTP: /health
      ADVERTISED_HOSTNAME: security-service
    depends_on:
      - eureka-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m30s
      timeout: 5s
      retries: 3

  blockchain-service:
    image: blockchain-service
    ports:
      - "8080"
    links:
      - eureka-server
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_SERV: http://eureka-server:8761/eureka/
      SERVICE_NAME: blockchain-service
      SERVICE_CHECK_HTTP: /health
      ADVERTISED_HOSTNAME: blockchain-service
    depends_on:
      - eureka-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m30s
      timeout: 5s
      retries: 3

  insurance-service:
    image: insurance-service
    ports:
      - "8080"
    links:
      - eureka-server
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_SERV: http://eureka-server:8761/eureka/
      SERVICE_NAME: insurance-service
      SERVICE_CHECK_HTTP: /health
      ADVERTISED_HOSTNAME: insurance-service
    depends_on:
      - eureka-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m30s
      timeout: 5s
      retries: 3